module.exports = {
    Plan: require('./plan.model'),
    User: require('./user.model'),
    Customer: require('./customer.model'),
    Restaurant: require('./restaurant.model'),
    RestaurantProfile: require('./restaurantProfile.model'),
    RestaurantRoom: require('./restaurantRoom.model'),
    RestaurantSpace: require('./restaurantSpace.model'),
    RestaurantSubscription: require('./restaurantSubscription.model'),
    Subscription: require('./subscription.model'),
    AvailabilityBlock: require('./availabilityBlock.model'),
    BookingRequest: require('./bookingRequest.model'),
    BookingMessage: require('./bookingMessage.model'),
    Event: require('./event.model'),
    Review: require('./review.model'),
    Media: require('./media.model'),
    Cuisine: require('./cuisine.model'),
    Inquiry: require('./inquiry.model'),
    SavedSpace: require('./savedSpace.model'),
    PDRConsultation: require('./pdrConsultation.model')
}
